# Generated by Django 4.1.6 on 2023-04-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGenerica', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='app_generica_objetos'),
        ),
    ]
